### ISSUE TITLE
come on

### ISSUE THREAD

**Issue by iamurdaddymyson** [caffeine-overload/bandinchina#126]
1. Tell me how you can always avoid all the correct understanding? 
2. You will not hesitate to provoke Beijing by means of killing Hong Kong，intending to make Beijing  fall into your trap, do you know the 《郑伯克段于鄢》？
3. The yellow umbrella can't cover the black atrocities, and the truth will eventually appear in front of the world, even if you delete more posts on Facebook and Twitter.Under the lofty slogan, hide your black evil, don't be ISIS
4. what behind the great , correct,and justice slogan“for freedom“ ，is the innocent children who are bullied, the  law enforcers who are slandered, the violence that be beautified, the traffic that be destoryed, the shops that be looted, the Dissidents who were besieged and beaten, just like the Cultural Revolution "for the people"，as well as Hitler ”For Germany“

**Comment by iamurdaddymyson** [comment]
See you ten years later

**Comment by iamurdaddymyson** [comment]
Poorly the murdered Hong Kong girl and her unborn kid, those who self-proclaimed justice
don’t care about it

**Comment by MoistCode** [comment]
@caffeine-overload This has got me thinking. Do you think we should have a Slack or Discord channel and add the link to the repo for these all types of discussions?

I think it would be beneficial so the issues don't get polluted with irrelevant items but people will still be able to converse. Plus, I wouldn't have to PM you on a random issue just to ask you something lol.

**Comment by iamurdaddymyson** [comment]
> @caffeine-overload This has got me thinking. Do you think we should have a Slack or Discord channel and add the link to the repo for these all types of discussions?
> 
> I think it would be beneficial so the issues don't get polluted with irrelevant items but people will still be able to converse. Plus, I wouldn't have to PM you on a random issue just to ask you something lol. I can also add the invitation link to the site so people who don't read READMEs can join as well.

Don't you think your repo has polluted github? Turning GitHub from a developer's paradise into a battleground for political struggles?

**Comment by caffeine-overload** [comment]
@iamurdaddymyson If you are worried about github being blocked in China due to this repo, don't worry. If the CCP complain, all github will do is block this particular repo. I don't think the CCP will dare block github in China due to how important it is for software development

**Comment by MoistCode** [comment]
I'm not sure what's going on. I just want to make a Slack or Discord channel for us lol.

**Comment by iamurdaddymyson** [comment]
> @iamurdaddymyson If you are worried about github being blocked in China due to this repo, don't worry. If the CCP complain, all github will do is block this particular repo. I don't think the CCP will dare block github in China due to how important it is for software development

Why am I worried about this? Do you understand correctly? Everywhere is ignited by the flames of your selfish political struggle. Everyone is forced to choose position. What is the difference between this and the Red Guard?

**Comment by iamurdaddymyson** [comment]
The protesters in Hong Kong used the Nazis way to accuse the police of injuring them. Beijing did not do anything but still be AOEed. Didn't they know that it would be directly killed by the US police in the United States?

**Comment by iamurdaddymyson** [comment]
I am not blaming you, I  hate this political struggle burnning to all the irrelevant places

**Comment by iamurdaddymyson** [comment]
How do you think about ZTE, Huawei and ALSTOM being subjected to persecution from the United States?Why not repo this to anti-washington

**Comment by iamurdaddymyson** [comment]
> I'm not sure what's going on. I just want to make a Slack or Discord channel for us lol.

My issue has been closed boy , again and again， don’t pretend to be liberal Guardian of Liberalism

**Comment by caffeine-overload** [comment]
I'm trying to find a way to explain my original motivation for this repo. Imagine if western governments started forcing Chinese companies to start punishing Chinese users in China for saying things that are controversial in Europe, and issue political apologies. I'm sure there would be outrage in China. 

You are free to not take a position. 

Nazism is a mix of ethno-nationalism (i.e. "superior ayran race"), scapegoating of foreigners and ethnic minorities, and the claiming of neighboring territory (lebensraum). The actions of the CCP resemble Nazism much more than HK protestors. You must have seen how frequently foreigners are baselessly accused of being spies and causing social issues. Europe has seen this cycle before, several times.

As for Hong Kong, none of the 5 demands impact Chinese sovereignty, and they don't even need the input of the CCP. The reports of violence against "innocent" mainlanders by Chinese media is embellished and sensationalized. The few mainlands who got attacked, provoked the crowd either by verbally threatening them or physically attacking them. Chinese media does not show this, in order to fuel their narrative and get clicks, just like conservative American media won't show Trump or US cops doing something bad. 

Same for the "looting", there was no looting. Look up videos of the London riots, that was looting. Looting is smashing into businesses and taking their produce, this has not happened in HK.
