### ISSUE TITLE
Hong Kong demonstrators, like a group of huge babies who have not grown up, are angry at all actions against their willings.

### ISSUE THREAD

**Issue by iamurdaddymyson** [caffeine-overload/bandinchina#144]

**Comment by ZeteticElench** [comment]
China's never-ending human rights abuses

• Hundreds of human rights lawyers (not even dissidents, just the LAWYERS who defended people) were snatched by gestapo all over China in what is known as the 709 Crackdown.

• One of those lawyers, Wang Quanzhang was sentenced to 4.5 years for "subversion of state power". But that's not enough. China actually went after Wang's 6-year-old son, forcing him out of his school and banning any other school from taking him in.

• A dissident, Wang Bingzhang was kidnapped by Chinese agents in Vietnam and sentenced to life in prison after a closed trial that lasted 1 day.

• A man wore a t-shirt with the word "Xitler" on it and was disappeared. Eventually he was tried for "subversion of state power" while barred from meeting with lawyers

• Another man, Wang Meiyu hold up a placard calling for Xi’s resignation & democracy. He was arrested for "picking quarrels”. He ended up dead in custody.

• A woman live streamed herself splashing ink on a Xi poster. She was disappeared. Her last social media update: "Right now there are a group of people wearing uniforms outside my door. I’ll go out after I change my clothes. I did not commit a crime. The people and groups that hurt me are the ones who are guilty". Later on there was report of her being sent to a psychiatric hospital

• After the ink-splash woman's disappearance her father made a series of broadcast to call attention to her plight. He ended up getting taken away by the police in the middle of a live stream

• 5 people associated with a Hong Kong bookstore that sold titles such as "Xi Jinping and His Six Women" were disappeared. Only one managed to escape back to HK. He held a press briefing to tell the world about his kidnapping by China. He's now in exile in Taiwan. The other 4 are still somewhere in China.

And, of course

• 1.5 million Uyghurs rounded up in concentration camps

• Leaked footage of a large number of blindfolded Uyghurs shackled together

• Genocide through forced abortions & sterilizations on Uyghur women

• Sexual torture of Uyghur women such as rape & rubbing intimate parts with chili paste.

• A Canadian journalist wanted to debunk reports of Chinese anti-Muslim repression so he went on a stage-managed show tour put on by China. That means he only saw a fake Potemkin village that China actually thought was acceptable by Western standard. But the brutality of even this fake Potemkin village stunned him. Now imagine what's really happening in the real concentration camps where millions of Uyghurs are being held. Imagine how bad the true situation is.

• Using minorities & political prisoners as free organ farms.

• Call for retraction of 400 Chinese scientific papers amid fears organs came from Chinese prisoners

• 15 Chinese studies retracted due to fears they used Chinese prisoners' organs

• Cultural genocide & organ harvests. A uyghur's testimony: "First, children were stopped from learning about the Quran, then from going to mosques. It was followed by bans on ramadan, growing beards, giving Islamic names to your baby, etc. Then our language was attacked – we didn’t get jobs if we didn’t know Mandarin. Our passports were collected, we were told to spy on each other, innocent Uyghur prisoners were killed for organ harvesting"

• Cultural genocide, part 2 destroy graveyards where generations of Uighur families are buried "to eradicate the ethnic group's identity"

• China is moving beyond Uyghur and cracking down on its model minority Hui Muslim. 'Afraid We Will Become The Next Xinjiang': China's Hui Muslims Face Crackdown: "The same restrictions that preceded the Xinjiang crackdown on Uighur Muslims are now appearing in Hui-dominated regions. Hui mosques have been forcibly renovated or shuttered, schools demolished, and religious community leaders imprisoned. Hui who have traveled internationally are increasingly detained or sent to reeducation facilities in Xinjiang."
