### ISSUE TITLE
When someone expresses a different position from the demonstrators, he will not only be defamed, beaten, or even receive death threats, and will  be stripped of clothes for Medieval-style shame

### ISSUE THREAD

**Issue by suckme1** [caffeine-overload/bandinchina#151]

**Comment by caffeine-overload** [comment]
I don't know whether to block you or just let you humiliate yourself on here for a while

**Comment by yourdaddy1111** [comment]
> I don't know whether to block you or just let you humiliate yourself on here for a while



> I don't know whether to block you or just let you humiliate yourself on here for a while

This is you, when others express different opinions, you block them, insult them, beat them.

**Comment by GoncaloBastos** [comment]
The misinformation machine in full throttle. It's quite entertaining

**Comment by yourdaddy1111** [comment]
![image](https://user-images.githubusercontent.com/57352137/68120947-815fb100-ff41-11e9-9d8b-3f5a012c66a7.png)

**Comment by yourdaddy1111** [comment]
> The misinformation machine in full throttle. It's quite entertaining

Yellow cloth is covered with your eyes, you still don't wake up

**Comment by caffeine-overload** [comment]
If this account was a disinformation asset his English would be good for starters. He is just a "patriotic citizen" reciting Chinese media soundbites and headlines. Of course their narrative is that all the violence comes from Hong Kongers, they don't mention that the "innocent Chinese victims" often started the violence by attacking people first. See https://www.bbc.co.uk/news/world-asia-china-50281914 , Chinese state media will paint him as an innocent victim and ignore the fact that he tried to commit a massacre.

**Comment by yourdaddy1111** [comment]
> If this account was a disinformation asset his English would be good for starters. He is just a "patriotic citizen" reciting Chinese media soundbites and headlines. Of course their narrative is that all the violence comes from Hong Kongers, they don't mention that the "innocent Chinese victims" often started the violence by attacking people first. See https://www.bbc.co.uk/news/world-asia-china-50281914 , Chinese state media will paint him as an innocent victim and ignore the fact that he tried to commit a massacre.

Why don't you try to speak Putonghua on the streets of Hong Kong?

**Comment by yourdaddy1111** [comment]
> If this account was a disinformation asset his English would be good for starters. He is just a "patriotic citizen" reciting Chinese media soundbites and headlines. Of course their narrative is that all the violence comes from Hong Kongers, they don't mention that the "innocent Chinese victims" often started the violence by attacking people first. See https://www.bbc.co.uk/news/world-asia-china-50281914 , Chinese state media will paint him as an innocent victim and ignore the fact that he tried to commit a massacre.

This is your logic. when someone have a different opinion from yours
, he/she will be attacked as an agent of CCP, so you convinced yourself that you are right.

**Comment by LenKagetsu** [comment]
> I don't know whether to block you or just let you humiliate yourself on here for a while

He'll just make a new account, maybe consider replying with [the copypasta](https://old.reddit.com/r/copypasta/comments/cw1dwz/how_to_ban_chinese_users_20/) when closing his tantrums until the CCP knocks on his door.

**Comment by yourdaddy1111** [comment]
> > I don't know whether to block you or just let you humiliate yourself on here for a while
> 
> He'll just make a new account, maybe consider replying with [the copypasta](https://old.reddit.com/r/copypasta/comments/cw1dwz/how_to_ban_chinese_users_20/) when closing his tantrums until the CCP knocks on his door.

lol , wow it is so simple! Do you  think that ccp has a monitor on everyone? Look, this is how Hitler smeared the Jews that year.

**Comment by yourdaddy1111** [comment]
> > I don't know whether to block you or just let you humiliate yourself on here for a while
> 
> He'll just make a new account, maybe consider replying with [the copypasta](https://old.reddit.com/r/copypasta/comments/cw1dwz/how_to_ban_chinese_users_20/) when closing his tantrums until the CCP knocks on his door.

During the Cold War, both the United States and the Soviet Union smeared each other as you did, and the Soviet Union failed. So the Soviet Union and China’s smearing against the United States disappeared, but the smearing against China  is still

**Comment by caffeine-overload** [comment]
@LenKagetsu The copypasta is an urban myth to be fair. Just report as spam

**Comment by Tsai-eng** [comment]
> @LenKagetsu The copypasta is an urban myth to be fair. Just report as spam

are you consider putting another homemade-bomb on the street?

**Comment by The1Freeman** [comment]
I've yet to see how the Nazis are involved in this, as it's clearly just sprouting bullshit over bullshit by making use of google translate, or his own poor attempts at writing english.
The stubbornness is something, I'll give you that, however you can't always be stuck in this delusional world in which you're being fed lies over and over again.

> @LenKagetsu The copypasta is an urban myth to be fair. Just report as spam
The urban myth isn't true, had to look it up.

**Comment by Tsai-eng** [comment]
> I've yet to see how the Nazis are involved in this (as I'm of German heritage), as it's clearly just sprouting bullshit over bullshit by making use of google translate, or his own poor attempts at writing english.
> The stubbornness is something, I'll give you that, however you can't always be stuck in this delusional world in which you're being fed lies over and over again.
> 
> > @LenKagetsu The copypasta is an urban myth to be fair. Just report as spam
> 
> The urban myth isn't true, had to look it up.

可能是你们的内鬼骗你们的哦嘻嘻，累了惹，不想趟蟑螂窝噜

**Comment by The1Freeman** [comment]
Und wenn du jetzt denkst in Chinesisch zu schreiben bringt dir irgendetwas, naja, du liegt falsch.
Was du damit erreichen willst ist und bleibt mir dennoch ein rätsel.

(And if you're thinking of writing in chinese now brings you something, well, you're wrong.
What you want to achieve with it is and still remains a mystery to me.)

**Comment by suckme1** [comment]
> Und wenn du jetzt denkst in Chinesisch zu schreiben bringt dir irgendetwas, naja, du liegt falsch.
> Was du damit erreichen willst ist und bleibt mir dennoch ein rätsel.
> 
> (And if you're thinking of writing in chinese now brings you something, well, you're wrong.
> What you want to achieve with it is and still remains a mystery to me.)

你是个可爱的小弟弟，啵~

**Comment by suckme1** [comment]
> Und wenn du jetzt denkst in Chinesisch zu schreiben bringt dir irgendetwas, naja, du liegt falsch.
> Was du damit erreichen willst ist und bleibt mir dennoch ein rätsel.
> 
> (And if you're thinking of writing in chinese now brings you something, well, you're wrong.
> What you want to achieve with it is and still remains a mystery to me.)

举头三尺有神淋，小心难逃一吸惹

**Comment by caffeine-overload** [comment]
You've changed your account name to  "your_daddy_suck_my_cock"

Real maturity there I see

**Comment by The1Freeman** [comment]
No way can you expect maturity from someone who actually compares todays events with WWII.

**Comment by ZeteticElench** [comment]
China's never-ending human rights abuses

• Hundreds of human rights lawyers (not even dissidents, just the LAWYERS who defended people) were snatched by gestapo all over China in what is known as the 709 Crackdown.

• One of those lawyers, Wang Quanzhang was sentenced to 4.5 years for "subversion of state power". But that's not enough. China actually went after Wang's 6-year-old son, forcing him out of his school and banning any other school from taking him in.

• A dissident, Wang Bingzhang was kidnapped by Chinese agents in Vietnam and sentenced to life in prison after a closed trial that lasted 1 day.

• A man wore a t-shirt with the word "Xitler" on it and was disappeared. Eventually he was tried for "subversion of state power" while barred from meeting with lawyers

• Another man, Wang Meiyu hold up a placard calling for Xi’s resignation & democracy. He was arrested for "picking quarrels”. He ended up dead in custody.

• A woman live streamed herself splashing ink on a Xi poster. She was disappeared. Her last social media update: "Right now there are a group of people wearing uniforms outside my door. I’ll go out after I change my clothes. I did not commit a crime. The people and groups that hurt me are the ones who are guilty". Later on there was report of her being sent to a psychiatric hospital

• After the ink-splash woman's disappearance her father made a series of broadcast to call attention to her plight. He ended up getting taken away by the police in the middle of a live stream

• 5 people associated with a Hong Kong bookstore that sold titles such as "Xi Jinping and His Six Women" were disappeared. Only one managed to escape back to HK. He held a press briefing to tell the world about his kidnapping by China. He's now in exile in Taiwan. The other 4 are still somewhere in China.

And, of course

• 1.5 million Uyghurs rounded up in concentration camps

• Leaked footage of a large number of blindfolded Uyghurs shackled together

• Genocide through forced abortions & sterilizations on Uyghur women

• Sexual torture of Uyghur women such as rape & rubbing intimate parts with chili paste.

• A Canadian journalist wanted to debunk reports of Chinese anti-Muslim repression so he went on a stage-managed show tour put on by China. That means he only saw a fake Potemkin village that China actually thought was acceptable by Western standard. But the brutality of even this fake Potemkin village stunned him. Now imagine what's really happening in the real concentration camps where millions of Uyghurs are being held. Imagine how bad the true situation is.

• Using minorities & political prisoners as free organ farms.

• Call for retraction of 400 Chinese scientific papers amid fears organs came from Chinese prisoners

• 15 Chinese studies retracted due to fears they used Chinese prisoners' organs

• Cultural genocide & organ harvests. A uyghur's testimony: "First, children were stopped from learning about the Quran, then from going to mosques. It was followed by bans on ramadan, growing beards, giving Islamic names to your baby, etc. Then our language was attacked – we didn’t get jobs if we didn’t know Mandarin. Our passports were collected, we were told to spy on each other, innocent Uyghur prisoners were killed for organ harvesting"

• Cultural genocide, part 2 destroy graveyards where generations of Uighur families are buried "to eradicate the ethnic group's identity"

• China is moving beyond Uyghur and cracking down on its model minority Hui Muslim. 'Afraid We Will Become The Next Xinjiang': China's Hui Muslims Face Crackdown: "The same restrictions that preceded the Xinjiang crackdown on Uighur Muslims are now appearing in Hui-dominated regions. Hui mosques have been forcibly renovated or shuttered, schools demolished, and religious community leaders imprisoned. Hui who have traveled internationally are increasingly detained or sent to reeducation facilities in Xinjiang."

**Comment by caffeine-overload** [comment]
@ZeteticElench Don't bother to engage, it is like trying to teach a barking dog poetry. 

Just report as spam/abuse
