### ISSUE TITLE
Hololive (Vtuber talent agency) suspends two of its streamers for showing that Taiwan is a country.

### ISSUE THREAD

**Issue by LenKagetsu** [caffeine-overload/bandinchina#169]
https://twitter.com/SavedYouAClickV/status/1310203802956562433
Translation of statement from bootlickers: https://ibb.co/52m1GW4
And of course, targeted harassment spearheaded by chinese nazis: https://twitter.com/_Vs_The_World/status/1310227045599805440?s=19

Of course we know who has a problem with people saying that. Saying that it was over them showing analytics is obviously a blatant lie, just like everything that comes out of the mouths of chinese nazis.

**Comment by LenKagetsu** [comment]
https://virtualyoutuber.fandom.com/wiki/Hololive If you're out of the loop on Hololive and Cover Corp

**Comment by hodolski** [comment]
Looks like the Hololive subreddit is also being raided.

**Comment by LenKagetsu** [comment]
> 
> 
> Looks like the Hololive subreddit is also being raided.

Indeed, I've seen a few of the "Totally generic name followed by numbers" bullshit on there. Always check the creation date of any and all accounts when something like this happens, along with comment history, these nazis follow a pretty obvious playbook.

**Comment by hodolski** [comment]
Vtubers hosted on Chinese platforms i.e. bilibili have always been controversial. For example, Kizuna Ai, the precursor of the industry, once added ROC flag in one of her thumbnails, and got raided from PRC. Despite some historical controversies, ongoing Senkaku Islands debate, and Japanese people being a bit racist to Chinese, the long-lasting economic regression have made Japanese businesses suck the warm teat.

**Comment by hodolski** [comment]
Cover Corp. doesn't give a flying fuck about their streamers' safety. Coco and Haato are receiving death threats from PRC, but Yagoo just tweets a link and says "Notify me if our talents are being harassed, duh." You know this is not the first time.

**Comment by hodolski** [comment]
[https://twitter.com/ashina_meaqua/status/1310195646117289984](https://twitter.com/ashina_meaqua/status/1310195646117289984)

Here's the Cover's statement on bilibili:
"Cover Corp. always respect the sovereignty of PRC and the Japan-China Joint Communique. Cover Corp. firmly supports the One-China Policy."

**Comment by hodolski** [comment]
Looking for any credible news article either in English or Japanese.
Korean ICT/Biz media Bloter covered this incident so far.
[http://www.bloter.net/archives/425929](http://www.bloter.net/archives/425929)

**Comment by caffeine-overload** [comment]
Yeah if there is no english source available non-english will do. Is there anything in Taiwanese newspapers I can link to?

**Comment by hodolski** [comment]
Sure thing. Just searched 日虛擬主播 (Japanese virtual streamer) and found these:

[https://tw.appledaily.com/international/20200927/5RC2MPFH2NHD3L5FL4JAUSRDKY/](https://tw.appledaily.com/international/20200927/5RC2MPFH2NHD3L5FL4JAUSRDKY/)
Japanese Vtubers mentioning "Taiwan" shatters the fragile hearts of the powerful mainland; management issues "stream suspension statement"

[https://m.ctee.com.tw/livenews/gj/chinatimes/20200928004376-260408](https://m.ctee.com.tw/livenews/gj/chinatimes/20200928004376-260408)
[https://www.chinatimes.com/realtimenews/20200928004376-260408?chdtv](https://www.chinatimes.com/realtimenews/20200928004376-260408?chdtv)
Japanese virtual internet celebrities stepped on the mainland's red line, calling Taiwan a country
(Both articles are the same, being of the same China Times Group.)

**Comment by hodolski** [comment]
For those new to the virtual YouTubers:

Virtual YouTubers (Vtubers) are streamers using motion-captured anime characters instead of real cams. Their real identities are usually kept secret. Kizuna Ai, debuted in 2016, is known for the precursor of this industry. Most Vtubers are streaming on YouTube as the name suggests, but you can find some on other platforms such as Twitch.

There are several streamer agencies dedicated to Vtubers: Cover's Hololive and Ichikara's Nijisanji to name a few. Hololive is one of the most active agencies, managing dozens of streamers and covering multiple regions. Kiryu Coco and Akai Haato are in the Japanese division, however, they also host on bilibili, the Chinese platform. Kiryu Coco, supposed but not verified to be American, is gaining popularity worldwide due to her distinct characteristics and fluent Japanese and English. Kiryu Coco won the top superchat earner on YouTube in August 2020. Akai Haato is also popular in Japan and overseas, being a relatively fluent English speaker and meme machine.
