### ISSUE TITLE
Chateau des ducs de Bretagne history museum in France kowtows after fascists take issue with their Genghis Khan exhibit.

### ISSUE THREAD

**Issue by LenKagetsu** [caffeine-overload/bandinchina#170]
https://www.theguardian.com/world/2020/oct/14/china-insists-genghis-khan-exhibit-not-use-words-genghis-khan

Imagine if a nazi demanded that a museum not say "Holocaust", "Kristallnacht", or "Auschwitz" and the museum compli- oh wait that's basically what just happened.

**Comment by caffeine-overload** [comment]
I'm keeping an eye on developments, but it actually looks to me like the museum took a stand, postponed the exhibition and denounced the Chinese demands rather than giving in. 

From what I understand the Chinese government demanded the exhibition go ahead but with a CCP approved narrative, rather than be canceled. 

DW [1] claims that they postponed the exhibition in order to find artifacts in western collections to display. I'm guessing if they ignored demands the museum in Hohhot they were collaborating with would refuse to co-operate and lend artifacts. 

I don't know why it would take 3 years to find replacement artifacts for exhibition, unless that's just how long these things take, I don't know how these things work. 

[1] https://www.dw.com/en/french-museum-says-china-tried-to-censor-genghis-khan-exhibit/a-55260696
