### ISSUE TITLE
Allow List

### ISSUE THREAD

**Issue by BlackAura** [caffeine-overload/bandinchina#19]
We try not to use the term whitelist in industry, and instead say allowlist.

It doesn't really make sense in this context, but I'd try to come up with something else.

**Comment by Faunsce** [comment]
Language policing like this is ridiculous. We dont need to worry about adapting to some kind of Orwellian programmer newspeak in order to try and talk on here.

**Comment by PrinceKael** [comment]
What's wrong with saying "Whitelist" ?

Are you saying because it's relevant to tech industry? Or because non-techies won't understand? Or because you're objecting to the use of "white"?

I can understand the second argument but I disagree, whitelist is a common term and the context it's in makes it easy for everyone to understand. If you're objecting to the use of "white" from a racial place, then I must certainly disagree as I don't see how that could possibly be an issue.

**Comment by LenKagetsu** [comment]
User literally made this account to post this in an attempt to harass and silence the developer, report, block, and ignore.

**Comment by BlackAura** [comment]
I've had this account since 2012 thank you very much, and have mostly used it for private personal projects.  I also have a professional account which sees much more use, but figured I should post this comment under my personal one since it's my own personal opinion.

![image](https://user-images.githubusercontent.com/687604/66680531-9dfc1800-ec25-11e9-8d14-324431415404.png)

I'd like to point out that I created this issue as a suggestion to the repository owner, and I was not attempting to police, harass, or silence anyone.  My phrasing clearly indicates that it's a suggestion, and I'm not saying the file should be removed, just renamed.

As to why I'm suggesting it?  It doesn't matter if you and I use those terms exclusively from a technology perspective.  If even one person has an issue with those terms, then it's a form of [casual racism](https://itstopswithme.humanrights.gov.au/what-can-you-do/speak/casual-racism).

My company has made an effort to stop using that terminology and to be more inclusive to everyone.

For a repository that is dedicated to showing when China has thrown their weight around to censor others or infringe on their rights, or to use the terminology above, silence them, you'd think they would try to be more politically correct in their choice of wording.

**Comment by BlackAura** [comment]
p.s. @LenKagetsu blocking/ignoring does the exact opposite of what you want in this situation, which is to foster open discussion.

My suggestion may be the exact opposite of what the repo owner wants, and that's fine, they're welcome to Close the issue with a "Won't Fix" status.  I'm also welcome to (assuming the licensing permits) fork the repo and make the modifications I want there.  That doesn't mean that my voice shouldn't be heard.

**Comment by Faunsce** [comment]
@BlackAura as you pointed out this repository is about chinese censorship and your suggestion is also censorship.

**Comment by MoistCode** [comment]
I understand where @BlackAura is coming from and there has been many discussions about the usage of the terms `blacklist` and `whitelist`. 

We must approach these terminologies with how people would perceive them when they first enter our repo/site only knowing that it represents being FOR the Democracy of Hong Kong and related matters.

Now if I see the words `allowlist` and `denylist`, I would ask what is it that they are allowing or denying? Are they allowing the Chinese government to do what they want or are they allowing Hong Kong to express their demands. The same can go for `denylist`.

If it helps, instead of using any of these, come up with a different term/phrase that makes it clear such as:

`whitelist` -> `Companies FOR the independence of Hong Kong`
`blacklist` -> `Companies AGAINST the independence of Hong Kong`

**Comment by caffeine-overload** [comment]
Closing for now, anyone feel free to open new issue if they have come up with good self-explanatory terminology
