### ISSUE TITLE
Make GH page mobile friendly

### ISSUE THREAD

**Issue by dmathisen** [caffeine-overload/bandinchina#34]
The github page looks awful on mobile. I think the best bet is to make this page more mobile friendly.
I also think that this page should be more prominent. Either in the title of the main GH page or something. It looks much better and there's more that can be done with it.
https://caffeine-overload.github.io/bandinchina/

Also, that red flag image is HUGE. Kind of obnoxiously huge.

Tagging @Medallyon who made the page. I don't mind working on the page to help make it better on mobile. But it's late. I'll check it out tomorrow if you don't get to it.

**Comment by dmathisen** [comment]
I worked on it a bit to make it mobile friendly. Pull request here...
https://github.com/caffeine-overload/bandinchina/pull/65

**Comment by Medallyon** [comment]
Hey, yeah, busy Friday.

I don't claim to be particularly good at designing websites, I just get stuff up and running. If you have any web design experience, feel free to contribute for sure.

I'm not sure how you'd go about making it more mobile-friendly since tables aren't the best thing anyway and I generally just rely on bootstrap to do that for me. Maybe parse the content and properly split it up into different sections as opposed to using a plain table on the site.

**Comment by dmathisen** [comment]
Cool. I'm more of a front-end/UI guy. I made it a bit more mobile-friendly but tables are def not easy. If the PR is accepted, I'll probably hide the "date added" column on mobile and that should help.

I'm also thinking of implemting datatables to have sort, search, pagination, etc...
https://datatables.net/examples/basic_init/zero_configuration.html
This also provides some better functionality for responsive design (hiding columns at different sizes, etc).

**Comment by MoistCode** [comment]
@dmathisen I did what I can for mobile friendly but I definitely think the tables could improve. It's a little more difficult to approach since there is quite a bit of information on them and stacking the information vertically won't do it as much justice.

I had some thoughts that I would definitely like to run by you.

We could possibly make the table headers fixed so when users get to the table and start scrolling through the data, they will always know what the data represent (i.e., company name or date added).

On the topic of how to structure the rows, we can make it so on mobile, only the company name show just like a drop down list. If a user wants more information about that company, they can just click on it and the rest of the information flows.

**Comment by dmathisen** [comment]
Hey @MoistCode. All good suggestions. Responsive tables are not easy. Regardless, I agree with fixed headers and/or pagination.

I've thought about using [datatables](https://datatables.net/) for the table, and I know that @MobiDotS made a [pull request](https://github.com/caffeine-overload/bandinchina/pull/74) to format the tables using [table sorter](https://mottie.github.io/tablesorter/docs/).

I'm not sure if those libraries help with responsiveness, but don't have time to look right now.
Also, the page has changed dramatically since I've seen it last... https://caffeine-overload.github.io/bandinchina/

**Comment by MoistCode** [comment]
@dmathisen Yeah the page did drastically change. Instead of being just a list of entities on both sides, there is also added information on how to help. Information is nice but action is also nice so might as well centralize things. Once the page is stable, I'm hoping people would spread the news of the new page and we'll get more contributors.

I can take a look into the table sorter in that PR and let you know if I can get that to work some time in the next few days.

**Comment by caffeine-overload** [comment]
Just to add, I still suggest additional HTML pages showing just the lists, so that mobile friendly lists can be directly linked to from elsewhere online during relevant discussions

**Comment by MoistCode** [comment]
> 
> 
> Just to add, I still suggest additional HTML pages showing just the lists, so that mobile friendly lists can be directly linked to from elsewhere online during relevant discussions

You're right @caffeine-overload. I can make that work. I'll create an issue for it.

**Comment by MobiDotS** [comment]
@MoistCode I rebased with latest changes so the table sorter should work on both lists now.
