### ISSUE TITLE
Free California, Free Hawaii, Free Guam, Free Alaska, they all should be independent, but occupied and controlled by brutal American whites

### ISSUE THREAD

**Issue by ThunderLT** [caffeine-overload/bandinchina#45]

**Comment by FoxyDysphoria** [comment]
lmao, bootlicker

**Comment by janicege** [comment]
@ThunderLT You know what? We don't really care if Californians want independence or not. 

The fact that you can rant freely here just proves how ignorant you are. Can anyone say Free Tibet and Free Hong Kong in China? I doubt and anyone doing so will be detained or deported by the government. You are just abusing the modern values for your CCP's agenda. What a world we live in now

**Comment by ThunderLT** [comment]
@janicege  So? Just like the Clippers’ racist remarks, they are expelled from the NBA. Is this your freedom of speech?

**Comment by ThunderLT** [comment]
@janicege  In China, openly expressing independent speech is as serious as the consequences of racist speech in the United States. If you are unhappy with me, you can let your American aircraft carrier and CIA come to China and Shanghai to take me away.

**Comment by ThunderLT** [comment]
@janicege  I said that white Americans are racist, oppressing African Americans, and only letting them play music. Statistically, among American capitalists and middle class, whites occupy most of the world.

**Comment by janicege** [comment]
@ThunderLT yes - you can say that racism is a serious issue in the US and I respect the issues you bring out. There are people working on this issue, but you just can't do the opposite in China by giving criticisms at all and saying anything different will be easily labeled as heretic. Come on, are you guys too sensitive?

**Comment by ThunderLT** [comment]
@janicege No, I think you have misunderstood that in China, it is not said that everything will be imprisoned. Only illegal acts such as the publication of Hong Kong’s independent speech will be punished (only legally handled and will not be killed). In China, many people curse Some inappropriate behaviors of the government and the Communist Party, but nothing at all. I have done this kind of thing myself before. As long as he is a legitimate act, he will only be punished for inciting Hong Kong’s independence, because this is Chinese. Taboos, like the publicly published racial discrimination in the United States, insulting the same serious behavior as blacks

**Comment by ThunderLT** [comment]
@janicege  In Hong Kong, many mobs actually carry illegal money through the money given by the CIA. They use weapons to violently attack ordinary children, women and police. Is this so-called freedom? If you are dissatisfied, you should pass legal Ways to protest, China allowed them to go on the streets, but violence is not allowed

**Comment by janicege** [comment]
@ThunderLT Ranting doesn’t help. 

From Day 1 and even until today, HK is not asking about independence and independence is never on the agenda of the demonstrations. A few raised such banners but it’s never a key voice in the city and it’s not pragmatic to most HK people. True, vandalism is wrong and those who commits these crimes should be prosecuted by the law enforcement but you cannot blackmouth and label all the demonstrators as “separatists" and ignore all the demands from the people. 

I’m not sure how well you know about the political structure in HK, which is part of your country’s affair. The chief is hand-picked by a pro-Beijing / pro-business dominated body of 1,200 and one of the demand people are asking are for more direct representation of their government by direct voting. 

The issue is already well advertised globally. I suggest you spend some time to understand the details of the causes. 

True, your government may suppress the demonstrators’ demand this time but the flaw of the system is still there. One day, the suppressed will come back again. 

Reference: 5 demands from protestors (SCMP is a pro-China newspaper in HK)
https://www.scmp.com/comment/letters/article/3031350/hong-kong-protesters-five-demands-are-purely-political-affordable

**Comment by cirosantilli** [comment]
See also: https://github.com/cirosantilli/china-dictatorship/tree/7a28a0658062698474073cad6967499d4095ca0e#western-democracies-have-invaded-other-countries-and-crushed-separatism

**Comment by ThunderLT** [comment]
@janicege I am afraid that you are the one who is unaware of the demands of Hong Kong claimants. This campaign begins with the fugitive offenders regulations. I suggest that you have a good understanding of the fugitive offenders. This is a normal and fair law. So far, it seems that you describe war The mob is one of the few demonstrators. My little sister is a native of Hong Kong. I have only been to Hong Kong three months ago. In fact, I am the witness of this incident. I suggest that you go to Hong Kong to see it instead of This hits the keyboard
