### ISSUE TITLE
Why closed issues."freedom of speech"? emm..

### ISSUE THREAD

**Issue by 784033619** [caffeine-overload/bandinchina#55]
The owner just wants to see what he want.So closed those he doesnt want? Freedom Of Speech!

**Comment by lazycrypt** [comment]
Because the owner of the repository can not fix the original issue, that is up to the maintaner of the Chinese Communist Party.

**Comment by ronchaine** [comment]
Because the issues have little to do with this repository, and are mainly just there as spam / mudslinging.  
They do not contribute to anything and are against GitHub ToS.

Such "issues" have better forum in places like Twitter, reddit or their Chinese equivalents, depending on your audience.  Or alternatively, there is nothing against opening your own repository, where those issues would be aligned with the repository content.

You can still see the closed issues, where this has been told by the repo owner as well.  Just spamming more isn't going to change it.


That being said, posts like @luiseok made, are just as much garbage as the issue itself.  Please don't lower yourself to OP's level, or degrade github to the level of 4chan, this is not the place for posts such as that.

**Comment by caffeine-overload** [comment]
I closed the first couple when the conversation died down, the rest I closed because it is clear that the people raising the issues aren't interested in having a conversation, just disrupting

You can still chat in a closed issue

Closing to unclutter the issues page
